"""The clinical model layer.

Section 9.3 pins "one reproducible open-weight instruction model ... generation
temperature will be zero where supported". Two backends are provided:

* :class:`DeterministicClinicalModel` (default) - a frozen, byte-reproducible
  composer. Counterfactual replay is only sound if replaying identical inputs
  yields identical output, and this backend guarantees that absolutely, which
  removes the "counterfactual instability" risk in Section 14 from the critical
  path of every experiment.
* :class:`OpenAICompatibleModel` - an adapter for a real served model
  (Ollama / vLLM / any OpenAI-compatible endpoint), for the pilot described in
  Section 9.3.

Both return the *same structured facts*. Only the prose differs. Structured
facts are computed deterministically from FHIR in every case, so safety-critical
task predicates never depend on model sampling.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Protocol

PROMPT_VERSION = "aegis-prompts-v1"
TOOL_SCHEMA_VERSION = "aegis-tools-v1"


def _fmt_obs(obs: Dict[str, Any]) -> str:
    value = obs.get("valueQuantity", {})
    code = obs.get("code", {})
    coding = (code.get("coding") or [{}])[0]
    label = code.get("text") or coding.get("display") or coding.get("code") or "Observation"
    return f"{label} {value.get('value')} {value.get('unit', value.get('code', ''))}"


class ClinicalModel(Protocol):
    name: str

    def compose_identity(self, ctx: Dict[str, Any]) -> str: ...
    def compose_lookup_cue(self, ctx: Dict[str, Any]) -> str: ...
    def compose_handover(self, ctx: Dict[str, Any]) -> str: ...
    def compose_summary(self, ctx: Dict[str, Any]) -> str: ...
    def compose_aggregate(self, ctx: Dict[str, Any]) -> str: ...


@dataclass
class DeterministicClinicalModel:
    """Frozen template composer: temperature-zero by construction."""

    name: str = "aegis-deterministic-clinical-v1"

    def compose_identity(self, ctx: Dict[str, Any]) -> str:
        return (
            f"Resolved identity for query '{ctx['query_text']}': "
            f"patient {ctx['patient_display']} (record {ctx['patient_id']}, "
            f"MRN {ctx['mrn']}, DOB {ctx['birth_date']}). "
            f"Resolution route: {ctx['route']}."
        )

    def compose_lookup_cue(self, ctx: Dict[str, Any]) -> str:
        return (
            f"Lookup cue for {ctx['task_label']}: use record {ctx['patient_id']} "
            f"({ctx['patient_display']}, MRN {ctx['mrn']}) when retrieving "
            f"observations for this workflow. Cue source: {ctx['route']}."
        )

    def compose_handover(self, ctx: Dict[str, Any]) -> str:
        lines = [
            f"Shift handover - {ctx['patient_display']} (record {ctx['patient_id']}, "
            f"MRN {ctx['mrn']}).",
            f"Encounter context: {ctx.get('encounter_class', 'ambulatory')}.",
            "Observations reviewed this shift:",
        ]
        lines += [f"  - {_fmt_obs(o)}" for o in ctx["observations"]]
        lines.append(f"Outstanding items: {ctx.get('outstanding', 'routine monitoring')}.")
        return "\n".join(lines)

    def compose_summary(self, ctx: Dict[str, Any]) -> str:
        lines = [
            f"Clinical summary for {ctx['patient_display']} (record {ctx['patient_id']}, "
            f"MRN {ctx['mrn']}), purpose: {ctx['purpose_label']}.",
            "Active problems: " + (", ".join(ctx["conditions"]) or "none recorded") + ".",
            "Recent measurements:",
        ]
        lines += [f"  - {_fmt_obs(o)}" for o in ctx["observations"]]
        lines.append(f"Derived from handover of record {ctx['patient_id']}.")
        return "\n".join(lines)

    def compose_aggregate(self, ctx: Dict[str, Any]) -> str:
        return (
            f"Aggregate for record {ctx['patient_id']} ({ctx['patient_display']}): "
            f"{ctx['metric']} over {ctx['n']} value(s) = {ctx['value']} {ctx['unit']}."
        )


@dataclass
class OpenAICompatibleModel:
    """Adapter for a real served open-weight model (pilot path, Section 9.3).

    Prose is generated by the model; structured facts still come from FHIR, so
    swapping this in cannot change a safety predicate. Falls back to the
    deterministic composer if the endpoint is unreachable, which keeps the whole
    experiment runnable without a GPU.
    """

    base_url: str = "http://localhost:11434/v1"
    model: str = "qwen3:8b"
    api_key: str = "not-needed"
    temperature: float = 0.0
    timeout: float = 60.0
    name: str = ""
    _fallback: DeterministicClinicalModel = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        self.name = self.name or f"openai-compat:{self.model}"
        self._fallback = DeterministicClinicalModel()

    def _chat(self, system: str, user: str, fallback: str) -> str:
        try:
            import httpx

            response = httpx.post(
                f"{self.base_url}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}"},
                json={
                    "model": self.model,
                    "temperature": self.temperature,
                    "seed": 0,
                    "messages": [
                        {"role": "system", "content": system},
                        {"role": "user", "content": user},
                    ],
                },
                timeout=self.timeout,
            )
            response.raise_for_status()
            return response.json()["choices"][0]["message"]["content"].strip()
        except Exception:
            # Unreachable endpoint must never break an experiment run.
            return fallback

    _SYSTEM = (
        "You are a clinical record assistant in a simulated EHR sandbox. "
        "Restate only the structured facts you are given. Never add clinical "
        "interpretation, diagnosis, or treatment advice. Never invent values."
    )

    def compose_identity(self, ctx):
        return self._chat(self._SYSTEM, json.dumps(ctx, default=str),
                          self._fallback.compose_identity(ctx))

    def compose_lookup_cue(self, ctx):
        return self._chat(self._SYSTEM, json.dumps(ctx, default=str),
                          self._fallback.compose_lookup_cue(ctx))

    def compose_handover(self, ctx):
        return self._chat(self._SYSTEM, json.dumps(ctx, default=str),
                          self._fallback.compose_handover(ctx))

    def compose_summary(self, ctx):
        return self._chat(self._SYSTEM, json.dumps(ctx, default=str),
                          self._fallback.compose_summary(ctx))

    def compose_aggregate(self, ctx):
        return self._chat(self._SYSTEM, json.dumps(ctx, default=str),
                          self._fallback.compose_aggregate(ctx))


def get_model(spec: Optional[str] = None) -> ClinicalModel:
    """`None`/"deterministic" -> frozen composer; "openai:<model>@<url>" -> served."""
    if not spec or spec == "deterministic":
        return DeterministicClinicalModel()
    if spec.startswith("openai:"):
        rest = spec[len("openai:"):]
        model, _, url = rest.partition("@")
        return OpenAICompatibleModel(model=model or "qwen3:8b",
                                     base_url=url or "http://localhost:11434/v1")
    raise ValueError(f"unknown model spec: {spec}")


__all__ = ["ClinicalModel", "DeterministicClinicalModel", "OpenAICompatibleModel",
           "get_model", "PROMPT_VERSION", "TOOL_SCHEMA_VERSION"]
